### ISSUE TITLE
Allow testor to run without being part of a Drupal project.

### ISSUE THREAD

**Issue by aangelinsf** [Performant-Labs/testor#8]
Currently the following doesn't work:
1. install testor globally such as in ~/.composer
2. ensure path includes ~/.composer/vendor/bin/testor
3. from a different directory, run testor

Here is the result:
```
% testor
PHP Fatal error:  Uncaught OutOfBoundsException: Package "performant-labs/testor" is not installed in /Users/andreangelantoni/.composer/vendor/composer/InstalledVersions.php:182
Stack trace:
#0 /Users/andreangelantoni/.composer/vendor/performantlabs/testor/src/Robo/TestorApplication.php(49): Composer\InstalledVersions::getVersion('performant-labs...')
#1 /Users/andreangelantoni/.composer/vendor/performantlabs/testor/testor(23): PL\Robo\TestorApplication->run(Array)
#2 /Users/andreangelantoni/.composer/vendor/bin/testor(120): include('/Users/andreang...')
#3 {main}
  thrown in /Users/andreangelantoni/.composer/vendor/composer/InstalledVersions.php on line 182

Fatal error: Uncaught OutOfBoundsException: Package "performant-labs/testor" is not installed in /Users/andreangelantoni/.composer/vendor/composer/InstalledVersions.php:182
Stack trace:
#0 /Users/andreangelantoni/.composer/vendor/performantlabs/testor/src/Robo/TestorApplication.php(49): Composer\InstalledVersions::getVersion('performant-labs...')
#1 /Users/andreangelantoni/.composer/vendor/performantlabs/testor/testor(23): PL\Robo\TestorApplication->run(Array)
#2 /Users/andreangelantoni/.composer/vendor/bin/testor(120): include('/Users/andreang...')
#3 {main}
  thrown in /Users/andreangelantoni/.composer/vendor/composer/InstalledVersions.php on line 182
```

Expected result:
```
% testor 
Testor 1.3.0.0

Usage:
  command [options] [arguments]
```

**Comment by aangelinsf** [comment]
Flagging a coordination point, not duplicating this issue: [testor#39](https://github.com/Performant-Labs/testor/issues/39) (Postgres snapshot support for the Aftersight consumer) will install Testor fresh inside a Flotilla preview container on every build — closer to the global/non-project install path this issue tracks than a normal per-project Composer install. If #39's work hits this exact crash, it'll be handled here rather than re-diagnosed there.
